config/routes.rb
Rails.application.routes.draw do



  root 'front#index'


  #resources :student
  get 'student/view_menu'
  get 'student/logout'
  get 'student/login'
  post 'student/login'
  get 'student/dashboard'
  get 'student/view_bill'
  get 'student/apply_mess_cut'
  post 'student/apply_mess_cut'
  get 'student/pay_bill'
  get 'student/purchase_history'
  get 'student/change_password'
  # We might not need this one
  post 'student/change_password'
  get 'student/feedback'
  post 'student/feedback'

  #resources :manager
  get 'manager/change_password'
  # We might not need this one
  post 'manager/change_password'
  get 'manager/dashboard'
  get 'manager/add_student'
  post 'manager/add_student'
  get 'manager/delete_student'
  post 'manager/delete_student'
  delete 'manager/delete_student'
   get 'manager/view_menu'
   post 'manager/view_menu'
   get'manager/login'
   post'manager/login'
  get 'manager/update_menu'
  post 'manager/update_menu'
resources :manager, :only => [:update_menu, :update_stock, :add_mess_cut, :update_mess_cut] do
  member do
    get :update_menu
    put :update_menu
    patch :update_menu
    get :update_stock
    put :update_stock
    patch :update_stock

    get :update_per_month_fee_detail
    put :update_per_month_fee_detail
    patch :update_per_month_fee_detail

     get :update_mess_cut
     put :update_mess_cut
     patch :update_mess_cut
    # get :add_mess_cut
    # put :add_mess_cut
    # patch :add_mess_cut

  end
end

  get 'manager/add_mess_cut'
  post 'manager/add_mess_cut'
#  get 'manager/update_mess_cut'
#  post 'manager/update_mess_cut'
  get 'manager/per_month_fee_detail'
  post 'manager/per_month_fee_detail'
  get 'manager/extra_per_day'
  post 'manager/extra_per_day'
  get 'manager/backup_db'
  get 'manager/view_stock'
  get 'manager/update_bill'
  get 'manager/monthly_profit_analysis'
  get 'manager/view_feedback'
  post 'manager/create'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/Manager.rb
class Menu < ApplicationRecord
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController

  def login
    #skip_before_filter :verify_authenticity_token
    if session[:admin] && session[:password]
      @result = Adminn.where(admin: session[:admin] , password: session[:password])
      if !@result.empty?
       redirect_to(manager_dashboard_path)
      end
    end

    if request.get?
      @logincred = Adminn.new
      @error = 0

    end

    if request.post?

      @logincred = Adminn.new(adminn_params)
    # @spassword = @logincred.password
      @result = Adminn.where(admin: @logincred.admin, password: @logincred.password)
    # If roll number and password exist
      if !@result.empty?
        session[:admin] = @logincred.admin
        session[:password] = @logincred.password
        session[:v] = 1

        redirect_to(manager_dashboard_path)

      else
        @error = 1
      end
      # @logintable = Login.all

    end
  end


  def logout
    @logincred = Adminn.new
    @error = 0
    session.clear
    render 'login'
  end



  def add_student

    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end
    if request.get?
      @student = Student.new
    end
    if request.post?
      @student = Student.new(student_params)
      if @student.save
        flash[:notice] = "Successfully created..."
        redirect_to(manager_add_student_path)
      end
   end
  end


  def delete_student
    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end
    if request.get?
      @student = Student.new
    end
    if request.post?
      @student = Student.find_by_roll_no(params[:student][:roll_no])
      @student.destroy
      flash[:notice] = "Successfully deleted '#{@student.name}'..."
      redirect_to(manager_delete_student_path)
    end
  end


  def view_menu
    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end
    if request.get?
      @menus = Menu.all
    end
    if request.post?
      @menu = Menu.find(params[:id])
    end
  end


  def update_menu
    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end
    @menu = Menu.find(params[:id])
    if request.patch?
      if  @menu.update_attributes(menu_params)
        flash[:notice] = "Successfully updated menu ... "
        redirect_to(manager_view_menu_path)
      end
    end
  end


  def add_mess_cut
    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end
    if request.get?
      @cuts = MessCut.all
    end
    if request.post?
      #@cut = MessCut.find(params[:id])
    end

  end

  def update_mess_cut
  #  @cut = MessCut.find(params[:id])
    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end
    @cut = MessCut.find(params[:id])
    if request.patch?
      if  @cut.update_attributes(mess_cut_params)
        flash[:notice] = "Successfully updated menu ... "
        redirect_to(manager_add_mess_cut_path)
      end
    end
  end

  def per_month_fee_detail
    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end

    if request.get?
      @bills = Bill.where(:status => '0')
    end
    if request.post?
      #@menu = Menu.find(params[:id])
    end

  end



  def update_per_month_fee_detail
    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end
    @bill = Bill.find(params[:id])
    if request.patch?
      if  @bill.update_attributes(fee_params)
        flash[:notice] = "Successfully updated menu ... "
        redirect_to(manager_per_month_fee_detail_path)
      end
    end
  end

  def extra_per_day
    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end
    if request.get?
      @extra = Extra.new
    end
    if request.post?
      @extra = Extra.new(extra_params)
      if @extra.save
        flash[:notice] = "Successfully created..."
        redirect_to(manager_extra_per_day_path)
      end
   end
  end

  def backup_db
    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end

    #system("backup perform -t ~/db_backup")
    #fork { exec 'backup perform -t db_backup' }

  end

  def view_stock
    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end
    if request.get?
      @stocks = Stock.all
    end
    if request.post?
        @stock = Stock.find(params[:id])
    end

  end

  def update_stock
    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end
    @stock = Stock.find(params[:id])
    if request.patch?
      if  @stock.update_attributes(stock_params)
        flash[:notice] = "Successfully updated stock ... "
        redirect_to(manager_view_stock_path)
      end
    end
  end

  def monthly_profit_analysis
    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end
  end

  def view_feedback
    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end

    @feedbacks = Feedback.all


  end

  def update_bill
    if ((session[:v] != 1) || !(session[:admin] || session[:password]))
      redirect_to(manager_login_path)
    end
  
    @students = Student.all
    @students.each do |f|
        @joined_date = Student.where(roll_no: f.roll_no).pluck(:created_at)[0]
        @joined_month = @joined_date.strftime("%B")
        @joined_day = @joined_date.strftime("%d")
        @joined_month_days = @joined_date.end_of_month.day
      # Including the day on which he joined
        @effective_days = @joined_month_days.to_i - @joined_day.to_i + 1
  
      # Calculate the number of mess cut days, that is the number of days for which the mess cut were accepted
        @mess_cut_days = 0
        @messcut_from_to = MessCut.where(roll_no: f.roll_no, status: "yes").order(:id).pluck(:from, :to)
        @messcut_from_to.each do |data|
          @mess_cut_days += data[1] - data[0] + 1
        end
  
      # No of days to charge for
        @chargeable_days = @effective_days - @mess_cut_days
  
      # Calculate extra's cost for that student
        @purchased = Extra.where(roll_no: f.roll_no).group('item').count('item')
        @purchase_total_cost = 0
        @purchased.each do |key, value|
          @cost = Item.where(item_name: key).pluck(:price)[0]
          @purchase_total_cost += @cost * value
        end
      # Calculating the total bill
      # Assuming base price = RS 80
        @total = @chargeable_days * 80 + @purchase_total_cost
        @bill = Bill.create(:roll_no => f.roll_no, :amount => @total, :status => '0', :month => Date::MONTHNAMES.index(@joined_month))
    end
  
  
    redirect_to(manager_login_path)
  
  end

  # def change_password
  #   if !(session[:roll_no] || session[:password])
  #     redirect_to(student_login_path)
  #   end
  #
  #   if request.get?
  #     @credentials = Adminn.new
  #     @savedornot = ""
  #   end
  #
  #   if request.post?
  #     @savedornot = ""
  #     @credentials = Adminn.new(adminn_params)
  #     @querydb = Adminn.where(roll_no: session[:roll_no], password: @credentials.admin)
  #     if !@querydb.empty?
  #       @savedornot = "Successfully Changed the password"
  #       @querydb[0].password = @credentials.password
  #       @querydb[0].save
  #     else
  #       @savedornot = "You entered wrong Old password"
  #     end
  #   end
  #
  #
  # end




end


private
  def student_params

    params.require(:student).permit(:name, :phone, :roll_no, :email, :password)

  end

  def menu_params
    params.require(:menu).permit(:day, :meal1, :meal2, :meal3)
  end

  def stock_params
    params.require(:stock).permit(:stock_id, :stock_name, :quantity, :cost_per_unit)
  end

  def adminn_params
    params.require(:adminn).permit(:admin, :password)
  end

  def extra_params
    params.require(:extra).permit(:roll_no, :item, :date)
  end

  def fee_params
    params.require(:bill).permit(:status)
  end

  def mess_cut_params
    params.require(:mess_cut).permit(:roll_no, :name, :from, :to, :status)
  end

  # def changepass_params
  #   params.require(:adminn).permit(:admin, :password)
  # end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/views/manager/add_mess_cut.html.erb
<h1>Manager#add_mess_cut</h1>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>


<table>
    <tr>

      <th>Roll_no</th>
      <th>Name</th>
      <th>From</th>
      <th>To</th>
      <th>Status</th>
    </tr>
   <% @cuts.each do |cut| %>
    <tr>
      <td><%= cut.roll_no %></td>
      <td class="center"><%= cut.name %></td>
      <td class="center"><%= cut.from %></td>
      <td class="center"><%= cut.to %></td>
      <td class="center"><%= cut.status %></td>
      <td class="action">
      <%= link_to("Update", update_mess_cut_manager_path(cut.id)) %>
      </td>

    </tr>
    <% end %>
  </table>

app/views/manager/add_student.html.erb
<h1>Manager#add_student</h1>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<%=form_for @student, url: {action: "add_student"} do |f| %>
<table summary="Subject form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Roll_no</th>
    <td><%= f.text_field(:roll_no) %></td>
  </tr>
  <tr>
    <th>Phone</th>
    <td><%= f.text_field(:phone) %></td>
  </tr>
  <tr>
    <th>Email</th>
    <td><%= f.text_field(:email) %></td>
  </tr>
  <tr>
    <th>Password</th>
    <td><%= f.text_field(:password) %></td>
  </tr>
</table>
      <%= f.submit("Add Student") %>
  <% end %>
</div>

app/views/manager/backup_db.html.erb
<h1>Manager#backup_db</h1>
<p>Find me in app/views/manager/backup_db.html.erb</p>

<% system ("backup perform -t db_backup") %>

app/views/manager/dashboard.html.erb
<h1>Welcome <%= session[:roll_no] %></h1>
<%= link_to("Add Student", manager_add_student_path) %>
<br>
<%= link_to("Delete Student", manager_delete_student_path ) %>
<br>
<%= link_to("View Menu", manager_view_menu_path ) %>
<br>
<%= link_to("Add Mess Cut", manager_add_mess_cut_path ) %>
<br>
<%= link_to("View Stocks", manager_view_stock_path ) %>
<br>
<%= link_to("View Feedback", manager_view_feedback_path) %>
<br>
<#%= link_to("logout", manager_logout_path) %>
<br>

app/views/manager/delete_student.html.erb
<h1>Manager#delete_student</h1>
<h2>Delete Student</h2>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<%=form_for @student, url: {action: "delete_student"} do |f| %>
<table summary="Subject form fields">
  <tr>
    <th>roll_no</th>
    <td><%= f.text_field(:roll_no) %></td>
  </tr>
  <tr>
  </table>
        <%= f.submit("Delete Student") %>
    <% end %>

app/views/manager/extra_per_day.html.erb
<h1>Manager#extra_per_day</h1>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<%=form_for @extra, url: {action: "extra_per_day"} do |f| %>
<table summary="Subject form fields">
  <tr>
    <th>roll_no</th>
    <td><%= f.text_field(:roll_no) %></td>
  </tr>
  <tr>
    <th>Item Id</th>
    <td><%= f.text_field(:item) %></td>
  </tr>
  <tr>
    <th>Date</th>
    <td><%= f.text_field(:date) %></td>
  </tr>

</table>
      <%= f.submit("Add Extra") %>
  <% end %>
</div>

app/views/manager/login.html.erb
<%= csrf_meta_tags %>

<% if @error == 1 %>
  <%="Oops something went wrong"%>
<% end %>
<%=form_for @logincred, url: {action: "login"} do |f| %>
<table summary="Subject form fields">
  <tr>
    <th style="text-align: left">Admin</th>
    <td><%= f.text_field(:admin) %></td>
  </tr>
  <tr>
    <th style="text-align: left">Password</th>
    <td><%= f.text_field(:password) %></td>
  </tr>
</table>
      <%= f.submit("Login") %>
<% end %>

app/views/manager/monthly_profit_analysis.html.erb
<h1>Manager#monthly_profit_analysis</h1>
<p>Find me in app/views/manager/monthly_profit_analysis.html.erb</p>

app/views/manager/per_month_fee_detail.html.erb
<h1>Manager#per_month_fee_detail</h1>
<table>
    <tr>

      <th>roll_no</th>
      <th>amount</th>
      <th>status</th>
      <th>month</th>
    </tr>
   <% @bills.each do |bill| %>
    <tr>

      <td class="center"><%= bill.roll_no %></td>
      <td class="center"><%= bill.amount %></td>
      <td class="center"><%= 'Pending' %></td>
      <td class="center"><%= Date::MONTHNAMES[bill.month] %></td>
      <td class="center">
      <%= link_to("Update", update_per_month_fee_detail_manager_path(bill.id)) %>
      </td>


    </tr>
    <% end %>
  </table>

app/views/manager/update_mess_cut.html.erb
<%=form_for @cut, url: {action: "update_mess_cut"} do |f| %>
<table summary="Subject form fields">
  <tr>
    <th>Status</th>
    <td><%= f.select :status, [['Approve', 'yes'], ['Deny', 'no']] %></td>
  </tr>
  <td><%= f.submit("Update") %></td>


<% end %>

app/views/manager/update_per_month_fee_detail.html.erb
<%=form_for @bill, url: {action: "update_per_month_fee_detail"} do |f| %>
<table summary="Subject form fields">
  <tr>
    <th>Status</th>
    <td><%= f.select :status, [['unpaid', 0], ['paid', 1]] %></td>
  </tr>
  <td><%= f.submit("Update") %></td>


<% end %>

app/views/manager/update_stock.html.erb
<h1>Manager#update_stock</h1>
<%=form_for @stock, url: {action: "update_stock"} do |f| %>
<table summary="Subject form fields">
  <tr>
    <th>stock_id</th>
    <td><%= f.text_field(:stock_id) %></td>
  </tr>
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:stock_name) %></td>
  </tr>
  <tr>
    <th>Quantity</th>
    <td><%= f.text_field(:quantity) %></td>
  </tr>
  <tr>
    <th>Cost Per Unit</th>
    <td><%= f.text_field(:cost_per_unit) %></td>
  </tr>
</table>
    <%= f.submit("Update") %>


<% end %>

app/views/manager/view_menu.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>


<table>
    <tr>

      <th>Day</th>
      <th>Meal 1</th>
      <th>Meal 2</th>
      <th>Meal 3</th>
    </tr>
   <% @menus.each do |menu| %>
    <tr>
      <td><%= menu.day %></td>
      <td class="center"><%= menu.meal1 %></td>
      <td class="center"><%= menu.meal2 %></td>
      <td class="center"><%= menu.meal3 %></td>
      <td class="action">
      <%= link_to("Update", update_menu_manager_path(menu.id)) %>
      </td>


    </tr>
    <% end %>
  </table>

app/views/manager/view_stock.html.erb
<h1>Manager#view_stock</h1>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<table>
    <tr>

      <th>Stock Id</th>
      <th>Stock Name</th>
      <th>Quantity</th>
      <th>Cost Per Unit</th>
    </tr>
   <% @stocks.each do |stock| %>
    <tr>
      <td><%= stock.stock_id %></td>
      <td class="center"><%= stock.stock_name %></td>
      <td class="center"><%= stock.quantity %></td>
      <td class="center"><%= stock.cost_per_unit %></td>
      <td>
      <%= link_to("Update", update_stock_manager_path(stock.id)) %>
      </td>
    </tr>

    <% end %>

  </table>