config/routes.rb
Rails.application.routes.draw do



  root 'front#index'


  #resources :student
  get 'student/view_menu'
  get 'student/logout'
  get 'student/login'
  post 'student/login'
  get 'student/dashboard'
  get 'student/view_bill'
  get 'student/apply_mess_cut'
  post 'student/apply_mess_cut'
  get 'student/pay_bill'
  get 'student/purchase_history'
  get 'student/change_password'
  # We might not need this one
  post 'student/change_password'
  get 'student/feedback'
  post 'student/feedback'

  #resources :manager
  get 'manager/change_password'
  # We might not need this one
  post 'manager/change_password'
  get 'manager/dashboard'
  get 'manager/add_student'
  post 'manager/add_student'
  get 'manager/delete_student'
  post 'manager/delete_student'
  delete 'manager/delete_student'
   get 'manager/view_menu'
   post 'manager/view_menu'
   get'manager/login'
   post'manager/login'
  get 'manager/update_menu'
  post 'manager/update_menu'
resources :manager, :only => [:update_menu, :update_stock, :add_mess_cut, :update_mess_cut] do
  member do
    get :update_menu
    put :update_menu
    patch :update_menu
    get :update_stock
    put :update_stock
    patch :update_stock

    get :update_per_month_fee_detail
    put :update_per_month_fee_detail
    patch :update_per_month_fee_detail

     get :update_mess_cut
     put :update_mess_cut
     patch :update_mess_cut
    # get :add_mess_cut
    # put :add_mess_cut
    # patch :add_mess_cut

  end
end

  get 'manager/add_mess_cut'
  post 'manager/add_mess_cut'
#  get 'manager/update_mess_cut'
#  post 'manager/update_mess_cut'
  get 'manager/per_month_fee_detail'
  post 'manager/per_month_fee_detail'
  get 'manager/extra_per_day'
  post 'manager/extra_per_day'
  get 'manager/backup_db'
  get 'manager/view_stock'
  get 'manager/update_bill'
  get 'manager/monthly_profit_analysis'
  get 'manager/view_feedback'
  post 'manager/create'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
# Login page for student
# Hackaround : Can we use direct variables here instead of using these class variables and all??
  def login
    if request.get?
      
      if session[:roll_no] && session[:password]
        @result = Student.where(roll_no: session[:roll_no] , password: session[:password])  
        if !@result.empty?
         redirect_to(student_dashboard_path)  
        end  
      end

      @logincred = Student.new
      @error = 0
    end

    if request.post?

      @logincred = Student.new(login_params)
    # @spassword = @logincred.password
      @result = Student.where(roll_no: @logincred.roll_no, password: @logincred.password)
    # If roll number and password exist
      if !@result.empty?
        session[:roll_no] = @logincred.roll_no
        session[:password] = @logincred.password
        redirect_to(student_dashboard_path)
      else
        @error = 1
      end
      # @logintable = Login.all

    end
  end

  def logout
    @logincred = Student.new
    @error = 0
    session.clear
    render 'login'
  end
# Dashboard for student
  def dashboard
    if !(session[:roll_no] || session[:password])
      redirect_to(student_login_path)  
    end
  end

  def view_menu
    if !(session[:roll_no] || session[:password])
      redirect_to(student_login_path)  
    end
    @menus = Menu.all
  end

  def view_bill
    if !(session[:roll_no] || session[:password])
      redirect_to(student_login_path) 
    end
# Get the number of days in the month in which the student joined
    @joined_date = Student.where(roll_no: session[:roll_no]).pluck(:created_at)[0]
    @joined_month = @joined_date.strftime("%B")
    @joined_day = @joined_date.strftime("%d")
    @joined_month_days = @joined_date.end_of_month.day
# Including the day on which he joined
    @effective_days = @joined_month_days.to_i - @joined_day.to_i + 1

# Calculate the number of mess cut days, that is the number of days for which the mess cut were accepted
    @mess_cut_days = 0
    @messcut_from_to = MessCut.where(roll_no: session[:roll_no], status: "yes").order(:id).pluck(:from, :to)
    @messcut_from_to.each do |data|
      @mess_cut_days += data[1] - data[0] + 1
    end

# No of days to charge for
    @chargeable_days = @effective_days - @mess_cut_days

# Calculate extra's cost for that student
    @purchased = Extra.where(roll_no: session[:roll_no]).group('item').count('item')
    @purchase_total_cost = 0
    @purchased.each do |key, value|
      @cost = Item.where(item_name: key).pluck(:price)[0]
      @purchase_total_cost += @cost * value
    end
# Calculating the total bill
# Assuming base price = RS 80 
    @total = @chargeable_days * 80 + @purchase_total_cost
  end

  def apply_mess_cut
    if !(session[:roll_no] || session[:password])
      redirect_to(student_login_path)  
    end

    if request.get?
      @messcut = MessCut.new
    end
    
    if request.post?
      @messcut = MessCut.new(messcut_params)
      if @messcut.save
        flash[:notice] = "Successfully submitted..."
      end
    end
  end

  def pay_bill
    if !(session[:roll_no] || session[:password])
      redirect_to(student_login_path)  
    end
      @currentbill = Bill.where(roll_no: session[:roll_no])
      @totalbill = 0
      if !@currentbill.empty?
        @currentbill.each do |data|
          @totalbill += data.amount
        end
      else
        @totalbill = -1
      end  
  end

  def purchase_history
    if !(session[:roll_no] || session[:password])
      redirect_to(student_login_path)  
    end
# Replace this hardcoded value with the session variables rollnumber and name
    # @purchased = Extra.where(roll_no: 123).group('item').count('item')
    @purchased = Extra.where(roll_no: session[:roll_no])

  end

  def change_password
    if !(session[:roll_no] || session[:password])
      redirect_to(student_login_path)  
    end

    if request.get?
      @credentials = Student.new
      @savedornot = ""
    end

    if request.post?
      @savedornot = ""
      @credentials = Student.new(changepass_params)
      @querydb = Student.where(roll_no: session[:roll_no], password: @credentials.email)
      if !@querydb.empty?
        @savedornot = "Successfully Changed the password"
        @querydb[0].password = @credentials.password
        @querydb[0].save
      else
        @savedornot = "You entered wrong Old password"
      end
    end


  end

  def feedback
    if !(session[:roll_no] || session[:password])
      redirect_to(student_login_path)  
    end
    
    if request.get?
      @feedback = Feedback.new
    end

    if request.post?
      @feedback = Feedback.new(feedback_params)
      if @feedback.save
        flash[:notice] = "Successfully created..."
      end
    end
  end
end

private
  def feedback_params
    params.require(:feedback).permit(:name, :s_id, :feedback)
  end

  def login_params
    params.require(:student).permit(:roll_no, :password)
  end

  def messcut_params
    params.require(:mess_cut).permit(:roll_no, :name, :from, :to)
  end
  
  def changepass_params
    params.require(:student).permit(:email, :password)
  end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/student/_ssidebar.html.erb
<div class="sidebar" data-color="purple" data-image="sidebar-1.jpg">
           
            <div class="logo">
                <a href="#" class="simple-text">
                   MMS
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li>
                        <a href="<%= student_dashboard_path %>">
                            <i class="material-icons">dashboard</i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li>
                        <a href="<%= student_view_menu_path %>">
                            <i class="material-icons">content_paste</i>
                            <p>View Menu</p>
                        </a>
                    </li>
                    <li>
                        <a href="<%= student_apply_mess_cut_path %>">
                            <i class="material-icons">content_cut</i>
                            <p>Apply Mess Cut</p>
                        </a>
                    </li>
                    <li>
                        <a href="<%= student_view_bill_path %>">
                            <i class="material-icons">library_books</i>
                            <p>View Bill</p>
                        </a>
                    </li>
                    <li>
                        <a href="<%= student_pay_bill_path %>">
                            <i class="material-icons">payment</i>
                            <p>Pay Bill</p>
                        </a>
                    </li>
                    <li>
                        <a href="<%= student_purchase_history_path %>">
                            <i class="material-icons">shopping_cart</i>
                            <p>Purchase History</p>
                        </a>
                    </li>
                    <li>
                        <a href="<%= student_change_password_path %>">
                            <i class="material-icons text-gray">settings</i>
                            <p>Change Password</p>
                        </a>
                    </li>
                    <li>
                        <a href="<%= student_feedback_path %>">
                            <i class="material-icons text-gray">feedback</i>
                            <p>Feedback</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

app/views/student/apply_mess_cut.html.erb
<div class="wrapper">
 <%= render 'ssidebar' %> 
        <div class="main-panel">
            <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                           
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"> Mess Cut </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    
                                    <p class="hidden-lg hidden-md">Dashboard</p>
                                </a>
                            </li>
                            
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    
                                    <p class="hidden-lg hidden-md">Profile</p>
                                </a>
                            </li>
                        </ul>
                        <form class="navbar-form navbar-right" role="search">
                            
                           
                                <%= link_to("logout", student_logout_path) %>
                               
                            
                        </form>
                    </div>
                </div>
	    </nav>
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Apply For Mess Cut</h4>
                                    <p class="category"></p>
                                </div>
                                <div class="card-content">
<%=form_for @messcut, url: {action: "apply_mess_cut"} do |f| %>
                                    <form>
                                        <div class="row">
                                            <div class="col-md-5">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">Roll No</label>
                                                    <%= f.text_field(:roll_no) %>
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">Name</label>
                                                    <%= f.text_field(:name) %>
                                                </div>
                                            </div>
                                           
                                        </div>
					<div class="row">
                                            <div class="col-md-5">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">From</label>
                                                    <%= f.text_field(:from) %>
                                                </div>
                                            </div>
					   <div class="col-md-3">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">To</label>
                                                    
						    <%= f.text_field(:to) %>
                                                </div>
                                            </div>
                                            
                                        </div>
                                 <%= f.submit("Apply") %>
				<% end %>
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    
                </div>
            </footer>
        </div>
    </div>

app/views/student/change_password.html.erb
<div class="wrapper">
       
	<%= render 'ssidebar' %> 
        <div class="main-panel">
           <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"> Settings </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    
                                    <p class="hidden-lg hidden-md">Dashboard</p>
                                </a>
                            </li>
                            
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    
                                    <p class="hidden-lg hidden-md">Profile</p>
                                </a>
                            </li>
                        </ul>
                        <form class="navbar-form navbar-right" role="search">
                            
                           
                                <%= link_to("logout", student_logout_path) %>
                               
                            
                        </form>
                    </div>
                </div>
</nav>
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Change Password</h4>
                                    <p class="category"></p>
                                </div>
                                <div class="card-content">
					<%= @savedornot %>
					<%= form_for @credentials, url: {action: "change_password"} do |f| %>
					<table >
					  <tr>
					    <th style="text-align: left">Old password</th>
					    <td><%= f.text_field(:email) %></td>
					  </tr>
					  <tr>
					    <th style="text-align: left">New Password</th>
					    <td><%= f.text_field(:password) %></td>
					  </tr>
					</table>
					      <%= f.submit("Change") %>
					<% end %>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    
                </div>
            </footer>
        </div>
    </div>

app/views/student/dashboard.html.erb
<div class="wrapper">
       
	<%= render 'ssidebar' %> 
        <div class="main-panel">
           <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"> Dashboard </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    
                                    <p class="hidden-lg hidden-md">Dashboard</p>
                                </a>
                            </li>
                            
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    
                                    <p class="hidden-lg hidden-md">Profile</p>
                                </a>
                            </li>
                        </ul>
                        <form class="navbar-form navbar-right" role="search">
                            
                           
                                <%= link_to("logout", student_logout_path) %>
                               
                            
                        </form>
                    </div>
                </div>
</nav>
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Welcome <%= session[:roll_no] %></h4>
                                    <p class="category"><%= session[:roll_no] %> Dashboard</p>
                                </div>
                                
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    
                </div>
            </footer>
        </div>
    </div>

app/views/student/feedback.html.erb
<div class="wrapper">
 <%= render 'ssidebar' %>
        <div class="main-panel">
            <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>

                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"> Feedback</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">

                                    <p class="hidden-lg hidden-md">Dashboard</p>
                                </a>
                            </li>

                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">

                                    <p class="hidden-lg hidden-md">Profile</p>
                                </a>
                            </li>
                        </ul>
                        <form class="navbar-form navbar-right" role="search">


                                <%= link_to("logout", student_logout_path) %>


                        </form>
                        </form>
                    </div>
                </div>
	    </nav>
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Feedback</h4>
                                    <p class="category"></p>
                                </div>
                                <div class="card-content">
<%=form_for @feedback, url: {action: "feedback"} do |f| %>
<table summary="Subject form fields">
  <tr>
    <th style="text-align: left;">s_id</th>
    <td><%= f.text_field(:s_id) %></td>
  </tr>
  <tr>
    <th style="text-align: left;">name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th style="text-align: left;">feedback</th>
    <td><%= f.text_field(:feedback) %></td>
  </tr>
</table>
      <%= f.submit("Add Student") %>
<% end %>

app/views/student/login.html.erb
<% if @error == 1 %>
  <%="Oops something went wrong"%>
<% end %>
<%=form_for @logincred, url: {action: "login"} do |f| %>
<table summary="Subject form fields">
  <tr>
    <th style="text-align: left">Roll Number</th>
    <td><%= f.text_field(:roll_no) %></td>
  </tr>
  <tr>
    <th style="text-align: left">Password</th>
    <td><%= f.text_field(:password) %></td>
  </tr>
</table>
      <%= f.submit("Login") %>
<% end %>

app/views/student/pay_bill.html.erb
<% if @totalbill != -1 %>
<h1>Your total Bill so far is</h1>
<p>Bill : Rs = <%= @totalbill %></p>
<a href="https://www.onlinesbi.com/prelogin/icollecthome.htm">Pay at SBI collect</a>
<% else %>
<h1>You don't have any outstanding bill !</h1>
<% end %>

app/views/student/purchase_history.html.erb
<div class="wrapper">
       
	<%= render 'ssidebar' %> 
        <div class="main-panel">
           <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"> Purchase </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    
                                    <p class="hidden-lg hidden-md">Dashboard</p>
                                </a>
                            </li>
                            
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    
                                    <p class="hidden-lg hidden-md">Profile</p>
                                </a>
                            </li>
                        </ul>
                        <form class="navbar-form navbar-right" role="search">
                            
                           
                                <%= link_to("logout", student_logout_path) %>
                               
                            
                        </form>
                    </div>
                </div>
</nav>
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Purchase History</h4>
                                    <p class="category"></p>
                                </div>
                                <div class="card-content">
					<table>
   						    <tr>
						      <th>Item name</th>
						      <th>Date</th>
						    </tr>
						   <% @purchased.each do |entry| %>
						    <tr>
						      <td><%= entry.item %></td>
						      <td ><%= entry.date %></td>
						    </tr>
						    <% end %>
						  </table>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    
                </div>
            </footer>
        </div>
    </div>

app/views/student/view_bill.html.erb
<div class="wrapper">
       
	<%= render 'ssidebar' %> 
        <div class="main-panel">
           <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"> Bill </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    
                                    <p class="hidden-lg hidden-md">Dashboard</p>
                                </a>
                            </li>
                            
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    
                                    <p class="hidden-lg hidden-md">Profile</p>
                                </a>
                            </li>
                        </ul>
                        <form class="navbar-form navbar-right" role="search">
                            
                           
                                <%= link_to("logout", student_logout_path) %>
                               
                            
                        </form>
                    </div>
                </div>
</nav>
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">View Bill</h4>
                                    <p class="category"></p>
                                </div>
                                <div class="card-content">
					<h1> Bill for the month of <%= @joined_month %> </h1>

					<h2>Rs : <%= @total.to_f %></h2>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    
                </div>
            </footer>
        </div>
    </div>